# Generated by Django 3.1.13 on 2021-10-14 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msgs', '0003_auto_20211013_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msg',
            name='room_assoc',
        ),
        migrations.AlterField(
            model_name='msg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
